/* -------------------------------------------------------------------------
 *  This file is part of the MindStudio project.
 * Copyright (c) 2025 Huawei Technologies Co.,Ltd.
 *
 * MindStudio is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 * ------------------------------------------------------------------------- */

#include <string>
#include <vector>
#include <cstdint>
#include "kernel_injection/include/MSBit.h"

namespace {
struct InstBindInfo {
    InstrType instrType;
    std::string funcName;
    std::vector<uint16_t> argsIndex;
    InstrForCore type;
};

std::vector<InstBindInfo> BIND_FUNCTION{
    // ccec type, stub function name, stub function args index
    {InstrType::ATOM_MAX_S_S32, "__msopprof_report_atom_max_s_s32", {}, InstrForCore::VEC},
    {InstrType::ATOM_MIN_S_S32, "__msopprof_report_atom_min_s_s32", {}, InstrForCore::VEC},
    {InstrType::ATOM_ADD_S_S32, "__msopprof_report_atom_add_s_s32", {}, InstrForCore::VEC},
    {InstrType::ATOM_ADD_S_U32, "__msopprof_report_atom_add_s_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_EXCH_S_U32, "__msopprof_report_atom_exch_s_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_MIN_S_U32, "__msopprof_report_atom_min_s_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_CAS_S_U32, "__msopprof_report_atom_cas_s_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_MAX_S_U32, "__msopprof_report_atom_max_s_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_EXCH_G_U64, "__msopprof_report_atom_exch_g_u64", {}, InstrForCore::VEC},
    {InstrType::ATOM_MIN_G_U64, "__msopprof_report_atom_min_g_u64", {}, InstrForCore::VEC},
    {InstrType::ATOM_ADD_G_U64, "__msopprof_report_atom_add_g_u64", {}, InstrForCore::VEC},
    {InstrType::ATOM_CAS_G_U64, "__msopprof_report_atom_cas_g_u64", {}, InstrForCore::VEC},
    {InstrType::ATOM_MAX_G_U64, "__msopprof_report_atom_max_g_u64", {}, InstrForCore::VEC},
    {InstrType::ATOM_ADD_G_S64, "__msopprof_report_atom_add_g_s64", {}, InstrForCore::VEC},
    {InstrType::ATOM_MIN_G_S64, "__msopprof_report_atom_min_g_s64", {}, InstrForCore::VEC},
    {InstrType::ATOM_MAX_G_S64, "__msopprof_report_atom_max_g_s64", {}, InstrForCore::VEC},
    {InstrType::ATOM_EXCH_G_U32, "__msopprof_report_atom_exch_g_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_MIN_G_U32, "__msopprof_report_atom_min_g_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_CAS_G_U32, "__msopprof_report_atom_cas_g_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_MAX_G_U32, "__msopprof_report_atom_max_g_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_ADD_G_U32, "__msopprof_report_atom_add_g_u32", {}, InstrForCore::VEC},
    {InstrType::ATOM_ADD_G_S32, "__msopprof_report_atom_add_g_s32", {}, InstrForCore::VEC},
    {InstrType::ATOM_MIN_G_S32, "__msopprof_report_atom_min_g_s32", {}, InstrForCore::VEC},
    {InstrType::ATOM_MAX_G_S32, "__msopprof_report_atom_max_g_s32", {}, InstrForCore::VEC},
    {InstrType::RED_S_U32, "__msopprof_report_red_s_u32", {}, InstrForCore::VEC},
    {InstrType::RED_S_BF16, "__msopprof_report_red_s_bf16", {}, InstrForCore::VEC},
    {InstrType::RED_S_S32, "__msopprof_report_red_s_s32", {}, InstrForCore::VEC},
    {InstrType::RED_S_FP16, "__msopprof_report_red_s_fp16", {}, InstrForCore::VEC},
    {InstrType::RED_S_FP32, "__msopprof_report_red_s_fp32", {}, InstrForCore::VEC},
    {InstrType::RED_G_BF16, "__msopprof_report_red_g_bf16", {}, InstrForCore::VEC},
    {InstrType::RED_G_U32, "__msopprof_report_red_g_u32", {}, InstrForCore::VEC},
    {InstrType::RED_G_F16X2, "__msopprof_report_red_g_f16x2", {}, InstrForCore::VEC},
    {InstrType::RED_G_S32, "__msopprof_report_red_g_s32", {}, InstrForCore::VEC},
    {InstrType::RED_G_FP32, "__msopprof_report_red_g_fp32", {}, InstrForCore::VEC},
    {InstrType::RED_G_BF16X2, "__msopprof_report_red_g_bf16x2", {}, InstrForCore::VEC},
    {InstrType::RED_G_FP16, "__msopprof_report_red_g_fp16", {}, InstrForCore::VEC},
    {InstrType::MUFU_F16, "__msopprof_report_mufu_f16", {}, InstrForCore::VEC},
    {InstrType::MUFU_F16X2, "__msopprof_report_mufu_f16x2", {}, InstrForCore::VEC},
    {InstrType::MUFU_F32, "__msopprof_report_mufu_f32", {}, InstrForCore::VEC},
    {InstrType::FFMA_F16, "__msopprof_report_ffma_f16", {}, InstrForCore::VEC},
    {InstrType::FFMA_F32, "__msopprof_report_ffma_f32", {}, InstrForCore::VEC},
    {InstrType::FFMA_V2F16, "__msopprof_report_ffma_f16x2", {}, InstrForCore::VEC},
    {InstrType::FFMA_BF16, "__msopprof_report_ffma_bf16", {}, InstrForCore::VEC},
    {InstrType::FFMA_V2BF16, "__msopprof_report_ffma_bf16x2", {}, InstrForCore::VEC},
    {InstrType::FFMA_F16_IMM, "__msopprof_report_ffma_imm_f16", {}, InstrForCore::VEC},
    {InstrType::FFMA_F32_IMM, "__msopprof_report_ffma_imm_f32", {}, InstrForCore::VEC},
    {InstrType::FFMA_V2F16_IMM, "__msopprof_report_ffma_imm_f16x2", {}, InstrForCore::VEC},
    {InstrType::FFMA_BF16_IMM, "__msopprof_report_ffma_imm_bf16", {}, InstrForCore::VEC},
    {InstrType::FFMA_V2BF16_IMM, "__msopprof_report_ffma_imm_bf16x2", {}, InstrForCore::VEC},
    {InstrType::FMUL_F16, "__msopprof_report_fmul_f16", {}, InstrForCore::VEC},
    {InstrType::FMUL_F16X2, "__msopprof_report_fmul_f16x2", {}, InstrForCore::VEC},
    {InstrType::FMUL_F32, "__msopprof_report_fmul_f32", {}, InstrForCore::VEC},
    {InstrType::FMUL_BF16, "__msopprof_report_fmul_bf16", {}, InstrForCore::VEC},
    {InstrType::FMUL_BF16X2, "__msopprof_report_fmul_bf16x2", {}, InstrForCore::VEC},
    {InstrType::FMUL_F16_IMM, "__msopprof_report_fmul_f16_imm", {}, InstrForCore::VEC},
    {InstrType::FMUL_F16X2_IMM, "__msopprof_report_fmul_f16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FMUL_F32_IMM, "__msopprof_report_fmul_f32_imm", {}, InstrForCore::VEC},
    {InstrType::FMUL_BF16_IMM, "__msopprof_report_fmul_bf16_imm", {}, InstrForCore::VEC},
    {InstrType::FMUL_BF16X2_IMM, "__msopprof_report_fmul_bf16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FADD_FP16, "__msopprof_report_fadd_fp16", {}, InstrForCore::VEC},
    {InstrType::FADD_FP32, "__msopprof_report_fadd_fp32", {}, InstrForCore::VEC},
    {InstrType::FADD_V2F16, "__msopprof_report_fadd_v2f16", {}, InstrForCore::VEC},
    {InstrType::FADD_BF16, "__msopprof_report_fadd_bf16", {}, InstrForCore::VEC},
    {InstrType::FADD_V2BF16, "__msopprof_report_fadd_v2bf16", {}, InstrForCore::VEC},
    {InstrType::FADD_FP16_IMM, "__msopprof_report_fadd_fp16_imm", {}, InstrForCore::VEC},
    {InstrType::FADD_FP32_IMM, "__msopprof_report_fadd_fp32_imm", {}, InstrForCore::VEC},
    {InstrType::FADD_FP16X2_IMM, "__msopprof_report_fadd_fp16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FADD_BF16_IMM, "__msopprof_report_fadd_bf16_imm", {}, InstrForCore::VEC},
    {InstrType::FADD_BF16X2_IMM, "__msopprof_report_fadd_bf16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FSETP_F16, "__msopprof_report_fsetp_f16", {}, InstrForCore::VEC},
    {InstrType::FSETP_F32, "__msopprof_report_fsetp_f32", {}, InstrForCore::VEC},
    {InstrType::FSETP_F16X2, "__msopprof_report_fsetp_f16x2", {}, InstrForCore::VEC},
    {InstrType::FSETP_BF16, "__msopprof_report_fsetp_bf16", {}, InstrForCore::VEC},
    {InstrType::FSETP_BF16X2, "__msopprof_report_fsetp_bf16x2", {}, InstrForCore::VEC},
    {InstrType::FSETP_F16_IMM, "__msopprof_report_fsetp_f16_imm", {}, InstrForCore::VEC},
    {InstrType::FSETP_F32_IMM, "__msopprof_report_fsetp_f32_imm", {}, InstrForCore::VEC},
    {InstrType::FSETP_F16X2_IMM, "__msopprof_report_fsetp_f16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FSETP_BF16_IMM, "__msopprof_report_fsetp_bf16_imm", {}, InstrForCore::VEC},
    {InstrType::FSETP_BF16X2_IMM, "__msopprof_report_fsetp_bf16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FMNMX_F16, "__msopprof_report_fmnmx_f16", {}, InstrForCore::VEC},
    {InstrType::FMNMX_F32, "__msopprof_report_fmnmx_f32", {}, InstrForCore::VEC},
    {InstrType::FMNMX_F16X2, "__msopprof_report_fmnmx_f16x2", {}, InstrForCore::VEC},
    {InstrType::FMNMX_BF16, "__msopprof_report_fmnmx_bf16", {}, InstrForCore::VEC},
    {InstrType::FMNMX_BF16X2, "__msopprof_report_fmnmx_bf16x2", {}, InstrForCore::VEC},
    {InstrType::FMNMX_F16_IMM, "__msopprof_report_fmnmx_f16_imm", {}, InstrForCore::VEC},
    {InstrType::FMNMX_F32_IMM, "__msopprof_report_fmnmx_f32_imm", {}, InstrForCore::VEC},
    {InstrType::FMNMX_F16X2_IMM, "__msopprof_report_fmnmx_f16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FMNMX_BF16_IMM, "__msopprof_report_fmnmx_bf16_imm", {}, InstrForCore::VEC},
    {InstrType::FMNMX_BF16X2_IMM, "__msopprof_report_fmnmx_bf16x2_imm", {}, InstrForCore::VEC},
    {InstrType::F2I_F16_U32, "__msopprof_report_f2i_f16_u32", {}, InstrForCore::VEC},
    {InstrType::F2I_F16_S32, "__msopprof_report_f2i_f16_s32", {}, InstrForCore::VEC},
    {InstrType::F2I_F32_U32, "__msopprof_report_f2i_f32_u32", {}, InstrForCore::VEC},
    {InstrType::F2I_F32_S32, "__msopprof_report_f2i_f32_s32", {}, InstrForCore::VEC},
    {InstrType::F2I_F32_U64, "__msopprof_report_f2i_f32_u64", {}, InstrForCore::VEC},
    {InstrType::F2I_F32_S64, "__msopprof_report_f2i_f32_s64", {}, InstrForCore::VEC},
    {InstrType::F2I_BF16_U32, "__msopprof_report_f2i_bf16_u32", {}, InstrForCore::VEC},
    {InstrType::F2I_BF16_S32, "__msopprof_report_f2i_bf16_s32", {}, InstrForCore::VEC},
    {InstrType::I2F_S32_BF16, "__msopprof_report_i2f_s32_bf16", {}, InstrForCore::VEC},
    {InstrType::I2F_S32_F16, "__msopprof_report_i2f_s32_f16", {}, InstrForCore::VEC},
    {InstrType::I2F_S64_F32, "__msopprof_report_i2f_s64_f32", {}, InstrForCore::VEC},
    {InstrType::I2F_U32_BF16, "__msopprof_report_i2f_u32_bf16", {}, InstrForCore::VEC},
    {InstrType::I2F_U32_F16, "__msopprof_report_i2f_u32_f16", {}, InstrForCore::VEC},
    {InstrType::I2F_U32_F32, "__msopprof_report_i2f_u32_f32", {}, InstrForCore::VEC},
    {InstrType::I2F_U64_F32, "__msopprof_report_i2f_u64_f32", {}, InstrForCore::VEC},
    {InstrType::F2F_F8E5M2X2_F32X2, "__msopprof_report_f2f_f8e5m2x2_f32x2", {}, InstrForCore::VEC},
    {InstrType::F2F_F16_F16, "__msopprof_report_f2f_f16_f16", {}, InstrForCore::VEC},
    {InstrType::F2F_F16_F32, "__msopprof_report_f2f_f16_f32", {}, InstrForCore::VEC},
    {InstrType::F2F_F16_BF16, "__msopprof_report_f2f_f16_bf16", {}, InstrForCore::VEC},
    {InstrType::F2F_F32_BF16, "__msopprof_report_f2f_f32_bf16", {}, InstrForCore::VEC},
    {InstrType::F2F_F32_F16, "__msopprof_report_f2f_f32_f16", {}, InstrForCore::VEC},
    {InstrType::F2F_F32_F32, "__msopprof_report_f2f_f32_f32", {}, InstrForCore::VEC},
    {InstrType::F2F_F32X2_BF16X2, "__msopprof_report_f2f_f32x2_bf16x2", {}, InstrForCore::VEC},
    {InstrType::F2F_F32X2_F16X2, "__msopprof_report_f2f_f32x2_f16x2", {}, InstrForCore::VEC},
    {InstrType::F2F_F32X2_HIF8X2, "__msopprof_report_f2f_f32x2_hif8x2", {}, InstrForCore::VEC},
    {InstrType::F2F_F32X2_F8E4M3X2, "__msopprof_report_f2f_f32x2_f8e4m3x2", {}, InstrForCore::VEC},
    {InstrType::F2F_F32X2_F8E5M2X2, "__msopprof_report_f2f_f32x2_f8e5m2x2", {}, InstrForCore::VEC},
    {InstrType::F2F_BF16_BF16, "__msopprof_report_f2f_bf16_bf16", {}, InstrForCore::VEC},
    {InstrType::F2F_BF16_FP16, "__msopprof_report_f2f_bf16_fp16", {}, InstrForCore::VEC},
    {InstrType::F2F_BF16_FP32, "__msopprof_report_f2f_bf16_fp32", {}, InstrForCore::VEC},
    {InstrType::F2F_F16X2_F32X2, "__msopprof_report_f2f_f16x2_f32x2", {}, InstrForCore::VEC},
    {InstrType::F2F_F16X2_HIF8X2, "__msopprof_report_f2f_f16x2_hif8x2", {}, InstrForCore::VEC},
    {InstrType::F2F_HIF8X2_F16X2, "__msopprof_report_f2f_hif8x2_f16x2", {}, InstrForCore::VEC},
    {InstrType::F2F_HIF8X2_F32X2, "__msopprof_report_f2f_hif8x2_f32x2", {}, InstrForCore::VEC},
    {InstrType::F2F_BF16X2_F32X2, "__msopprof_report_f2f_bf16x2_f32x2", {}, InstrForCore::VEC},
    {InstrType::F2F_F8E4M3X2_F32X2, "__msopprof_report_f2f_f8e4m3x2_f32x2", {}, InstrForCore::VEC},
    {InstrType::FDIV_F16, "__msopprof_report_fdiv_f16", {}, InstrForCore::VEC},
    {InstrType::FDIV_F16X2, "__msopprof_report_fdiv_f16x2", {}, InstrForCore::VEC},
    {InstrType::FDIV_F32, "__msopprof_report_fdiv_f32", {}, InstrForCore::VEC},
    {InstrType::FDIV_F16_IMM, "__msopprof_report_fdiv_f16_imm", {}, InstrForCore::VEC},
    {InstrType::FDIV_F16X2_IMM, "__msopprof_report_fdiv_f16x2_imm", {}, InstrForCore::VEC},
    {InstrType::FDIV_F32_IMM, "__msopprof_report_fdiv_f32_imm", {}, InstrForCore::VEC},
    {InstrType::FEXPDIF_FMIX, "__msopprof_report_fexpdif_fmix", {}, InstrForCore::VEC},
    {InstrType::FEXPDIF_F32, "__msopprof_report_fexpdif_f32", {}, InstrForCore::VEC},
    {InstrType::IMAD_S32, "__msopprof_report_imad_s32", {}, InstrForCore::VEC},
    {InstrType::IMAD_U32, "__msopprof_report_imad_u32", {}, InstrForCore::VEC},
    {InstrType::IMAD_HI_U32, "__msopprof_report_imad_hi_u32", {}, InstrForCore::VEC},
    {InstrType::IMAD_HI_S32, "__msopprof_report_imad_hi_s32", {}, InstrForCore::VEC},
    {InstrType::IMAD_WIDE_U32, "__msopprof_report_imad_wide_u32", {}, InstrForCore::VEC},
    {InstrType::IMAD_WIDE_S32, "__msopprof_report_imad_wide_s32", {}, InstrForCore::VEC},
    {InstrType::IMAD_NORM_U32_IMM, "__msopprof_report_imad_norm_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IMAD_NORM_S32_IMM, "__msopprof_report_imad_norm_s32_imm", {}, InstrForCore::VEC},
    {InstrType::IMAD_HI_S32_IMM, "__msopprof_report_imad_hi_s32_imm", {}, InstrForCore::VEC},
    {InstrType::IMAD_HI_U32_IMM, "__msopprof_report_imad_hi_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IMAD_WIDE_S32_IMM, "__msopprof_report_imad_wide_s32_imm", {}, InstrForCore::VEC},
    {InstrType::IMAD_WIDE_U32_IMM, "__msopprof_report_imad_wide_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IMAD_X_S32, "__msopprof_report_imad_x_s32", {}, InstrForCore::VEC},
    {InstrType::IMAD_X_U32, "__msopprof_report_imad_x_u32", {}, InstrForCore::VEC},
    {InstrType::IMAD_X_S32_IMM, "__msopprof_report_imad_x_s32_imm", {}, InstrForCore::VEC},
    {InstrType::IMAD_X_U32_IMM, "__msopprof_report_imad_x_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IMUL_NORM_U32, "__msopprof_report_imul_norm_u32", {}, InstrForCore::VEC},
    {InstrType::IMUL_NORM_S32, "__msopprof_report_imul_norm_s32", {}, InstrForCore::VEC},
    {InstrType::IMUL_HI_S32, "__msopprof_report_imul_hi_s32", {}, InstrForCore::VEC},
    {InstrType::IMUL_HI_U32, "__msopprof_report_imul_hi_u32", {}, InstrForCore::VEC},
    {InstrType::IMUL_WIDE_S32, "__msopprof_report_imul_wide_s32", {}, InstrForCore::VEC},
    {InstrType::IMUL_WIDE_U32, "__msopprof_report_imul_wide_u32", {}, InstrForCore::VEC},
    {InstrType::IMUL_NORM_U32_IMM, "__msopprof_report_imul_norm_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IMUL_NORM_S32_IMM, "__msopprof_report_imul_norm_s32_imm", {}, InstrForCore::VEC},
    {InstrType::IMUL_HI_U32_IMM, "__msopprof_report_imul_hi_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IMUL_HI_S32_IMM, "__msopprof_report_imul_hi_s32_imm", {}, InstrForCore::VEC},
    {InstrType::IMUL_WIDE_S32_IMM, "__msopprof_report_imul_wide_s32_imm", {}, InstrForCore::VEC},
    {InstrType::IMUL_WIDE_U32_IMM, "__msopprof_report_imul_wide_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IADD, "__msopprof_report_iadd", {}, InstrForCore::VEC},
    {InstrType::IADD_IMM, "__msopprof_report_iadd_imm", {}, InstrForCore::VEC},
    {InstrType::IADD_X, "__msopprof_report_iadd_x", {}, InstrForCore::VEC},
    {InstrType::IADD_X_IMM, "__msopprof_report_iadd_x_imm", {}, InstrForCore::VEC},
    {InstrType::ISETP_S32_IMM, "__msopprof_report_isetp_s32_imm", {}, InstrForCore::VEC},
    {InstrType::ISETP_U32_IMM, "__msopprof_report_isetp_u32_imm", {}, InstrForCore::VEC},
    {InstrType::ISETP_S32, "__msopprof_report_isetp_s32", {}, InstrForCore::VEC},
    {InstrType::ISETP_U32, "__msopprof_report_isetp_u32", {}, InstrForCore::VEC},
    {InstrType::IMNMX_U32, "__msopprof_report_imnmx_u32", {}, InstrForCore::VEC},
    {InstrType::IMNMX_S32, "__msopprof_report_imnmx_s32", {}, InstrForCore::VEC},
    {InstrType::IMNMX_U32_IMM, "__msopprof_report_imnmx_u32_imm", {}, InstrForCore::VEC},
    {InstrType::IMNMX_S32_IMM, "__msopprof_report_imnmx_s32_imm", {}, InstrForCore::VEC},
    {InstrType::LEA_HI_X_B32, "__msopprof_report_lea_hi_x_b32", {}, InstrForCore::VEC},
    {InstrType::LEA_HI_X_SX32, "__msopprof_report_lea_hi_x_sx32", {}, InstrForCore::VEC},
    {InstrType::LEA_HI_X_ZX32, "__msopprof_report_lea_hi_x_zx32", {}, InstrForCore::VEC},
    {InstrType::SHF_U32, "__msopprof_report_shf_u32", {}, InstrForCore::VEC},
    {InstrType::SHF_S32, "__msopprof_report_shf_s32", {}, InstrForCore::VEC},
    {InstrType::SHF_U64, "__msopprof_report_shf_u64", {}, InstrForCore::VEC},
    {InstrType::SHF_S64, "__msopprof_report_shf_s64", {}, InstrForCore::VEC},
    {InstrType::SHFI_S32, "__msopprof_report_shfi_s32", {}, InstrForCore::VEC},
    {InstrType::SHFI_U32, "__msopprof_report_shfi_u32", {}, InstrForCore::VEC},
    {InstrType::SHFI_S64, "__msopprof_report_shfi_s64", {}, InstrForCore::VEC},
    {InstrType::SHFI_U64, "__msopprof_report_shfi_u64", {}, InstrForCore::VEC},
    {InstrType::MAD_S8, "__msopprof_report_mad_s8", {0, 1, 2, 3}},
    {InstrType::MAD_F16_F32, "__msopprof_report_mad_f16_f32", {0, 1, 2, 3}},
    {InstrType::MAD_BF16_F32, "__msopprof_report_mad_bf16_f32", {0, 1, 2, 3}},
    {InstrType::MAD_F32_F32, "__msopprof_report_mad_f32_f32", {0, 1, 2, 3}},
    {InstrType::MAD_E4M3_E4M3, "__msopprof_report_mad_e4m3_e4m3", {0, 1, 2, 3}},
    {InstrType::MAD_E4M3_E5M2, "__msopprof_report_mad_e4m3_e5m2", {0, 1, 2, 3}},
    {InstrType::MAD_E5M2_E4M3, "__msopprof_report_mad_e5m2_e4m3", {0, 1, 2, 3}},
    {InstrType::MAD_E5M2_E5M2, "__msopprof_report_mad_e5m2_e5m2", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E1M2X2_E1M2X2, "__msopprof_report_mad_mx_e1m2_e1m2", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E1M2X2_E2M1X2, "__msopprof_report_mad_mx_e1m2_e2m1", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E2M1X2_E1M2X2, "__msopprof_report_mad_mx_e2m1_e1m2", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E2M1X2_E2M1X2, "__msopprof_report_mad_mx_e2m1_e2m1", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E4M3_E4M3, "__msopprof_report_mad_mx_e4m3_e4m3", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E4M3_E5M2, "__msopprof_report_mad_mx_e4m3_e5m2", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E5M2_E4M3, "__msopprof_report_mad_mx_e5m2_e4m3", {0, 1, 2, 3}},
    {InstrType::MAD_MX_E5M2_E5M2, "__msopprof_report_mad_mx_e5m2_e5m2", {0, 1, 2, 3}},
};
}

extern "C" {
void MSBitAtInit()
{
    for (auto it: BIND_FUNCTION) {
        Bind(it.instrType, it.funcName, it.argsIndex, it.type);
    }
}
}
